[package]
name = "screenguard"
version = "0.2.1"
description = "跨平台显示器控制与色彩/多屏助手"
authors = ["陆冠霖"]
edition = "2021"

[lib]
name = "screenguard_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api", "tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
lto = true
codegen-units = 1
strip = true
